import type { HlcTimestamp } from './hlc';

/**
 * Represents a single operation in a JSON Patch (RFC 6902).
 */
export type PatchOperation =
  | { op: 'add'; path: string; value: any }
  | { op: 'remove'; path: string }
  | { op: 'replace'; path: string; value: any }
  | { op: 'move'; from: string; path: string }
  | { op: 'copy'; from: string; path: string }
  | { op: 'test'; path: string; value: any };

/**
 * A JSON Patch is a sequence of operations.
 */
export type JsonPatch = PatchOperation[];

/**
 * An Operation is the atomic unit of change within the SyncState system.
 * It encapsulates a patch, its target document, and metadata for ordering
 * and conflict resolution.
 */
export interface Operation {
  /**
   * A unique, chronologically-sortable ID generated by a Hybrid Logical Clock.
   * This is the primary key for an operation and determines its place in the log.
   */
  id: HlcTimestamp;

  /**
   * The unique identifier of the client session that generated this operation.
   */
  clientId: string;

  /**
   * The identifier for the document or state subtree this operation applies to.
   */
  docId: string;

  /**
   * The set of changes to be applied, formatted as a JSON Patch.
   */
  patch: JsonPatch;
}
